-- CreateEnum
CREATE TYPE "FoodType" AS ENUM ('MEET', 'VEGETABLE', 'FRUIT', 'SEAFOOD', 'OTHER');

-- AlterTable
ALTER TABLE "Food" ADD COLUMN     "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "type" "FoodType" NOT NULL DEFAULT 'OTHER',
ADD COLUMN     "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
